apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  labels:
    app: traefik
spec:
  selector:
    app: traefik
  type: LoadBalancer  # or NodePort, depending on your cluster environment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: admin
