apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.consul.persistence.size }}
  storageClassName: {{ .Values.consul.persistence.storageClass }}
