apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra.fullname" . }}-consul
  labels:
    app: consul
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.consul.port }}
    targetPort: {{ .Values.consul.port }}
  selector:
    app: consul
