apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra.fullname" . }}-fabio
  labels:
    app: fabio
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.fabio.port }}
    targetPort: {{ .Values.fabio.port }}
  selector:
    app: fabio
