apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra.fullname" . }}-grafana
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.grafana.port }}
    targetPort: {{ .Values.grafana.port }}
  selector:
    app: grafana
