apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
stringData:
  username: {{ .Values.mongo.credentials.username | quote }}
  password: {{ .Values.mongo.credentials.password | quote }}
