apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra.fullname" . }}-mongo
  labels:
    app: mongo
spec:
  ports:
  - port: {{ .Values.mongo.port }}
    targetPort: {{ .Values.mongo.port }}
  clusterIP: None
  selector:
    app: mongo
