apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra.fullname" . }}-prometheus
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.prometheus.port }}
    targetPort: {{ .Values.prometheus.port }}
  selector:
    app: prometheus
