apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.seq.persistence.size }}
  storageClassName: {{ .Values.seq.persistence.storageClass }}
