apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra.fullname" . }}-vault
  labels:
    app: vault
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.vault.port }}
    targetPort: {{ .Values.vault.port }}
  selector:
    app: vault
