apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pupitre-foundation.yaml
  - pupitre-ai.yaml
  - pupitre-support.yaml
  - pupitre-data.yaml
  - pupitre-observability.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0"
