apiVersion: v1
kind: Namespace
metadata:
  name: pupitre-data
  labels:
    app.kubernetes.io/name: pupitre
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: pupitre-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-quota
  namespace: pupitre-data
spec:
  hard:
    requests.cpu: "30"
    requests.memory: 100Gi
    limits.cpu: "60"
    limits.memory: 200Gi
    pods: "50"
    persistentvolumeclaims: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: data-limits
  namespace: pupitre-data
spec:
  limits:
    - default:
        cpu: "2"
        memory: 8Gi
      defaultRequest:
        cpu: "500m"
        memory: 2Gi
      type: Container
