apiVersion: v1
kind: Namespace
metadata:
  name: pupitre-support
  labels:
    app.kubernetes.io/name: pupitre
    app.kubernetes.io/component: support
    app.kubernetes.io/part-of: pupitre-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: support-quota
  namespace: pupitre-support
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    pods: "100"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: support-limits
  namespace: pupitre-support
spec:
  limits:
    - default:
        cpu: "1"
        memory: 1Gi
      defaultRequest:
        cpu: "100m"
        memory: 256Mi
      type: Container
