apiVersion: v1 # String
kind: Pod  # String
metadata: # Dictionary
  name: fbdetb-online-banking-web-pod
  labels: # Dictionary 
    app: fbdetb-online-banking-web         
spec:
  containers: # List
    - name: fbdetb-online-banking-web
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80
