replicaCount: 2
image: "mamey-io/mamey-bank-gateway:latest"
service:
  port: 80
ingress:
  enabled: true
  hostname: "internal.api.mamey.example.com"
  whitelist: "10.0.0.0/8,192.168.1.0/24"  # Only accessible from internal networks.
