apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "internal-api-gateway.fullname" . }}
  labels:
    app: internal-api-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: internal-api-gateway
  template:
    metadata:
      labels:
        app: internal-api-gateway
    spec:
      containers:
      - name: internal-api-gateway
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: {{ .Values.service.port }}
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: {{ .Values.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
