apiVersion: v1
kind: Service
metadata:
  name: {{ include "internal-api-gateway.fullname" . }}
  labels:
    app: internal-api-gateway
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: internal-api-gateway
