version: '3.4'

services:
  mamey.bank.webserver:
    image: ${DOCKER_REGISTRY-}mameybank
    build:
      context: .
      dockerfile: ../Mamey.Bank.WebServer/src/Mamey.Bank.WebServer/Dockerfile
