version: '3'

services:
  mamey.fwid.operations-service:
    build:
      context: ../
      dockerfile: Mamey.FWID.Operations/Dockerfile
      args:
        FEED_URL: ${FEED_URL}
        FEED_PAT: ${FEED_PAT}
        FEED_NAME: ${FEED_NAME}
        FEED_USERNAME: ${FEED_USERNAME}
    image: mamey.fwid.operations-service
    container_name: mamey.fwid.operations-service
    env_file: 
      - ./.env-development
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${Certificates__Default__Path}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${Certificates__Default__Password}
    restart: unless-stopped
    ports:
      - 5007:443
      - 5007:80
    networks:
      - mamey
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

networks:
  mamey:
    name: mamey
    external: true


